language: cpp

compiler: gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python
- sudo apt-get install -qq gcc-5.4 g++-5.4

script:
- mkdir gcc
- python convert_to_one_file.py
- g++-5.4 gcc/main.cpp -std=c++11 -o gcc/main