language: cpp

compiler: gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python

script:
- mkdir gcc
- python convert_to_one_file.py
- $CXX gcc/main.cpp -std=c++0x -o gcc/main